spring:
  datasource:
    url: jdbc:postgresql://dpg-clvjameg1b2c73ch8p30-a:5432/db_java_project_72?password=QCRJLS4eEM8rSZ87DUewKOzT4Xzd6Tb9&user=db_java_project_72_user

sentry:
  dsn: https://24b0dadd1e516198ba0b927db76227b4@o4506712353275904.ingest.sentry.io/4506712395939840
  sentry.traces-sample-rate: 1.0
  environment: production